name: CI/CD for streamlit App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests (Pytest)
        run:  | 
          pytest tests/test_app.py
      
      - name: Deploy to Streamlit Cloud
        run: |
          curl -sSL https://streamlit.io/downloads/streamlit-cloud-cli.tar.gz | tar xz
          ./streamlit-cloud-cli deploy .

